### ISSUE TITLE
"exhausted input" when trying to get Json response from page with "Transfer-Encoding - chunked"

### ISSUE THREAD

**Issue by invis87** [amrhassan/scala-httpc#31]
Try to send simple GET request to page https://poloniex.com//public?command=returnTradeHistory&currencyPair=USDT_ETH

```
val url = "https://poloniex.com//public?command=returnTradeHistory&currencyPair=USDT_ETH"
val command = get(url)

run(command) match {
      case Left(error)     => logger.error("Error on request", error)
      case Right(response) => {
        logger.info(response.json.toString)
        logger.info(s"Receive response:\nStatus: ${response.status}\nHeaders: ${response.headers.map(h => s"${h.name} - ${h.value}").mkString("; ")}\nBody: ${response.body}")
      }
    }
```

You will see next output:
```
[info] [06-Nov-2016 13:27:41] INFO  [main] - Left(io.circe.ParsingFailure: exhausted input)
[info] [06-Nov-2016 13:27:41] INFO  [main] - Receive response:
[info] Status: Status(200)
[info] Headers: Date - Sun, 06 Nov 2016 11:27:40 GMT; Content-Type - application/json; Transfer-Encoding - chunked; Connection - keep-alive; Set-Cookie - __cfduid=dc3074b3d9a79c7783b0ca519c860e2ba1478431660; expires=Mon, 06-Nov-17 11:27:40 GMT; path=/; domain=.poloniex.com; HttpOnly; Access-Control-Allow-Origin - *; Access-Control-Allow-Methods - GET; Server - cloudflare-nginx; CF-RAY - 2fd83295c98d169a-ARN
[info] Body: ByteVector(empty)
```

**Comment by amrhassan** [comment]
This should be fixed now. Please try again with the latest snapshot from sonatype.

**Comment by invis87** [comment]
If you didn't change version ("0.3.0-SNAPSHOT"), then it is still not working.
I remove all files related to `httpc` repository from my `coursier` cache, then redownload it and still not working.

**Comment by amrhassan** [comment]
Can you please delete `~/.ivy2/cache/io.github.amrhassan/` and try again. I'm in the process of making a versioned release today to decrease this hassle.

**Comment by invis87** [comment]
I use `sbt-coursier`, so there is no such directory `~/.ivy2/cache/io.github.amrhassan/`
And after removing `.coursier/cache/v1/https/jcenter.bintray.com/io/github/amrhassan/httpc_2.11` and redownloading it again it still don't work...
After I remove `sbt-coursier` plugin and redownloading you repository - All worked :)
Thanks for fix!
